### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by demianrey** [JtMotoX/purevpn-proxy#1]
Hello, first of all thanks for your work, but I could not start the service, I get the following error
![Screenshot_2022-01-20-19-05-26-628_com sonelli juicessh](https://user-images.githubusercontent.com/48655207/150447095-a9db6e32-7466-4102-9e7a-5d7fa1a6aa8b.jpg)
Regards

**Comment by JtMotoX** [comment]
Can you please try with --verbose and provide the logs?

```bash
docker-compose --verbose up
```

**Comment by demianrey** [comment]
> ```shell
> docker-compose --verbose up
> ```
**of course this is the result**
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.auth.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.auth.find_config_file: No config file found
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/version HTTP/1.1" 200 802
compose.cli.command.get_client: docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
compose.cli.command.get_client: Docker base_url: http+docker://localunixsocket
compose.cli.command.get_client: Docker version: KernelVersion=4.15.0-50-generic, Components=[{u'Version': u'20.10.7', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.15.0-50-generic', u'Os': u'linux', u'BuildTime': u'2021-10-22T00:57:37.000000000+00:00', u'ApiVersion': u'1.41', u'MinAPIVersion': u'1.12', u'GitCommit': u'20.10.7-0ubuntu5~18.04.3', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.13.8'}}, {u'Version': u'1.5.5-0ubuntu3~18.04.1', u'Name': u'containerd', u'Details': {u'GitCommit': u''}}, {u'Version': u'1.0.1-0ubuntu2~18.04.1', u'Name': u'runc', u'Details': {u'GitCommit': u''}}, {u'Version': u'0.19.0', u'Name': u'docker-init', u'Details': {u'GitCommit': u''}}], Arch=amd64, BuildTime=2021-10-22T00:57:37.000000000+00:00, ApiVersion=1.41, Platform={u'Name': u''}, Version=20.10.7, MinAPIVersion=1.12, GitCommit=20.10.7-0ubuntu5~18.04.3, Os=linux, GoVersion=go1.13.8
compose.cli.verbose_proxy.proxy_callable: docker info <- ()
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/info HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker info -> {u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'CgroupVersion': u'1',
 u'ContainerdCommit': {u'Expected': u'', u'ID': u''},
 u'Containers': 0,
 u'ContainersPaused': 0,
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- (u'purevpnproxy_default')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/networks/purevpnproxy_default HTTP/1.1" 200 525
compose.cli.verbose_proxy.proxy_callable: docker inspect_network -> {u'Attachable': True,
 u'ConfigFrom': {u'Network': u''},
 u'ConfigOnly': False,
 u'Containers': {},
 u'Created': u'2022-01-20T21:51:26.417847977Z',
 u'Driver': u'bridge',
 u'EnableIPv6': False,
 u'IPAM': {u'Config': [{u'Gateway': u'172.18.0.1',
                        u'Subnet': u'172.18.0.0/16'}],
           u'Driver': u'default',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'purevpnproxy_nfs-transmission-downloads')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/volumes/purevpnproxy_nfs-transmission-downloads HTTP/1.1" 200 414
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2022-01-20T21:51:26Z',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'purevpnproxy',
             u'com.docker.compose.volume': u'nfs-transmission-downloads'},
 u'Mountpoint': u'/var/lib/docker/volumes/purevpnproxy_nfs-transmission-downloads/_data',
 u'Name': u'purevpnproxy_nfs-transmission-downloads',
 u'Options': {u'device': u':/volume1/Transmission/downloads',
              u'o': u'addr=192.168.168.40,rw',
              u'type': u'nfs'},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'purevpnproxy_nfs-transmission-downloads')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/volumes/purevpnproxy_nfs-transmission-downloads HTTP/1.1" 200 414
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2022-01-20T21:51:26Z',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'purevpnproxy',
             u'com.docker.compose.volume': u'nfs-transmission-downloads'},
 u'Mountpoint': u'/var/lib/docker/volumes/purevpnproxy_nfs-transmission-downloads/_data',
 u'Name': u'purevpnproxy_nfs-transmission-downloads',
 u'Options': {u'device': u':/volume1/Transmission/downloads',
              u'o': u'addr=192.168.168.40,rw',
              u'type': u'nfs'},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={u'label': [u'com.docker.compose.project=purevpnproxy', u'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?all=0&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dpurevpnproxy%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0 HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=purevpnproxy', u'com.docker.compose.service=purevpn', u'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dpurevpnproxy%22%2C+%22com.docker.compose.service%3Dpurevpn%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0 HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('jtmotox/purevpn-proxy:latest')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/images/jtmotox/purevpn-proxy:latest/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {u'Architecture': u'amd64',
 u'Author': u'',
 u'Comment': u'',
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/bash'],
             u'Domainname': u'',
             u'Entrypoint': [u'/scripts/entrypoint.sh'],
             u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=purevpnproxy', u'com.docker.compose.service=purevpn', u'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dpurevpnproxy%22%2C+%22com.docker.compose.service%3Dpurevpn%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0 HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: set([<Service: purevpn>])
compose.parallel.feed_queue: Starting producer thread for <Service: purevpn>
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=purevpnproxy', u'com.docker.compose.service=purevpn', u'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dpurevpnproxy%22%2C+%22com.docker.compose.service%3Dpurevpn%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0 HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
Creating purevpn-proxy ...
compose.parallel.feed_queue: Pending: set([1])
compose.parallel.feed_queue: Starting producer thread for 1
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('jtmotox/purevpn-proxy:latest')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/images/jtmotox/purevpn-proxy:latest/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {u'Architecture': u'amd64',
 u'Author': u'',
 u'Comment': u'',
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/bash'],
             u'Domainname': u'',
             u'Entrypoint': [u'/scripts/entrypoint.sh'],
             u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('jtmotox/purevpn-proxy:latest')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/images/jtmotox/purevpn-proxy:latest/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {u'Architecture': u'amd64',
 u'Author': u'',
 u'Comment': u'',
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/bash'],
             u'Domainname': u'',
             u'Entrypoint': [u'/scripts/entrypoint.sh'],
             u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
...
compose.service.build_container_labels: Added config hash: 4c0775d08a675a2e3f95ae750204423240d156d32f1733e17b6d40b2c04b2a69
compose.cli.verbose_proxy.proxy_callable: docker create_host_config <- (device_read_iops=None, mem_swappiness=None, links=[], oom_score_adj=None, cpu_count=None, pids_limit=None, cpuset_cpus=None, dns_search=None, pid_mode=None, init_path=None, log_config={'Type': u'', 'Config': {}}, cpu_quota=None, read_only=None, cpu_percent=None, device_read_bps=None, storage_opt=None, init=None, dns=None, volumes_from=[], ipc_mode=None, mem_reservation=None, security_opt=None, shm_size=None, device_write_iops=None, dns_opt=None, cgroup_parent=None, group_add=None, network_mode=u'purevpnproxy_default', blkio_weight_device=None, userns_mode=None, tmpfs=None, nano_cpus=None, port_bindings={'9091/tcp': ['9091'], '1080/tcp': ['1080']}, isolation=None, memswap_limit=None, restart_policy={u'MaximumRetryCount': 0, u'Name': u'no'}, volume_driver=None, devices=None, extra_hosts=None, binds=[u'/root/purevpn-proxy/transmission/resume:/var/lib/transmission-daemon/.config/transmission-daemon/resume:rw', u'/root/purevpn-proxy/build/scripts:/scripts:rw', u'/etc/localtime:/etc/localtime:ro', u'purevpnproxy_nfs-transmission-downloads:/var/lib/transmission-daemon/downloads:rw', u'/root/purevpn-proxy/transmission/torrents:/var/lib/transmission-daemon/.config/transmission-daemon/torrents:rw'], sysctls=None, blkio_weight=None, device_write_bps=None, cap_add=None, mem_limit=None, cap_drop=None, privileged=True, ulimits=None, cpu_shares=None)
compose.cli.verbose_proxy.proxy_callable: docker create_host_config -> {'Binds': [u'/root/purevpn-proxy/transmission/resume:/var/lib/transmission-daemon/.config/transmission-daemon/resume:rw',
           u'/root/purevpn-proxy/build/scripts:/scripts:rw',
           u'/etc/localtime:/etc/localtime:ro',
           u'purevpnproxy_nfs-transmission-downloads:/var/lib/transmission-daemon/downloads:rw',
           u'/root/purevpn-proxy/transmission/torrents:/var/lib/transmission-daemon/.config/transmission-daemon/torrents:rw'],
 'Links': [],
 'LogConfig': {'Config': {}, 'Type': u''},
 'NetworkMode': u'purevpnproxy_default',
 'PortBindings': {'1080/tcp': [{'HostIp': '', 'HostPort': '1080'}],
                  '9091/tcp': [{'HostIp': '', 'HostPort': '9091'}]},
...
compose.service.create_container: Creating purevpn-proxy
compose.cli.verbose_proxy.proxy_callable: docker create_container <- (hostname='purevpn-proxy', name='purevpn-proxy', image='jtmotox/purevpn-proxy:latest', labels={u'com.docker.compose.service': u'purevpn', u'com.docker.compose.project': u'purevpnproxy', u'com.docker.compose.config-hash': '4c0775d08a675a2e3f95ae750204423240d156d32f1733e17b6d40b2c04b2a69', u'com.docker.compose.version': u'1.17.1', u'com.docker.compose.oneoff': u'False', u'com.docker.compose.container-number': '1'}, host_config={'NetworkMode': u'purevpnproxy_default', 'Links': [], 'PortBindings': {'9091/tcp': [{'HostPort': '9091', 'HostIp': ''}], '1080/tcp': [{'HostPort': '1080', 'HostIp': ''}]}, 'LogConfig': {'Type': u'', 'Config': {}}, 'Binds': [u'/root/purevpn-proxy/transmission/resume:/var/lib/transmission-daemon/.config/transmission-daemon/resume:rw', u'/root/purevpn-proxy/build/scripts:/scripts:rw', u'/etc/localtime:/etc/localtime:ro', u'purevpnproxy_nfs-transmission-downloads:/var/lib/transmission-daemon/downloads:rw', u'/root/purevpn-proxy/transmission/torrents:/var/lib/transmission-daemon/.config/transmission-daemon/torrents:rw'], 'RestartPolicy': {u'MaximumRetryCount': 0, u'Name': u'no'}, 'Privileged': True, 'VolumesFrom': []}, environment=[u'purevpn_password=***', u'proxy_service=3proxy', u'killswitch=true', u'rpc_whitelist=127.0.0.1,192.168.*.*', u'allow_subnet=192.168.50.0/24', u'purevpn_location=MX', u'rpc_authentication_required=false', u'purevpn_username=***'], volumes={u'/var/lib/transmission-daemon/.config/transmission-daemon/resume': {}, u'/scripts': {}, u'/etc/localtime': {}, u'/var/lib/transmission-daemon/downloads': {}, u'/var/lib/transmission-daemon/.config/transmission-daemon/torrents': {}}, detach=True, ports=[(u'1080', u'tcp'), (u'9091', u'tcp')], networking_config={u'EndpointsConfig': {u'purevpnproxy_default': {u'IPAMConfig': {}, u'Aliases': ['purevpn']}}})
compose.parallel.feed_queue: Pending: set([])
**this last line is repeated many times**
.
.
.

ERROR: for purevpn-proxy  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
compose.parallel.parallel_execute_iter: Failed: <Service: purevpn>
compose.parallel.feed_queue: Pending: set([])

ERROR: for purevpn  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: compose.cli.errors.log_timeout_error: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by JtMotoX** [comment]
It might be the `nfs-transmission-downloads` volume that is hanging it up.  The docker-compose.yml file is configured to mount a remote nfs volume to store Transmission downloads.

Can you please comment out the entire `volumes:` section in the top of your `docker-compose.yml` and also comment out the `- nfs-transmission-downloads:` line in `volumes:` section in the bottom of your `docker-compose.yml`?

```yaml
version: '3'

# volumes:
#     nfs-transmission-downloads:
#         driver: local
#         driver_opts:
#             type: nfs
#             o: addr=192.168.168.40,rw
#             device: ":/volume1/Transmission/downloads"

services:
    purevpn:
        build: ./build
        image: jtmotox/purevpn-proxy:latest
        container_name: purevpn-proxy
        env_file: my.env
        hostname: purevpn-proxy
        privileged: true
        restart: "no"
        ports:
            - "1080:1080" # socks5 proxy
            - "9091:9091" # transmission
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./build/scripts:/scripts
            # - nfs-transmission-downloads:/var/lib/transmission-daemon/downloads
            - ./transmission/resume:/var/lib/transmission-daemon/.config/transmission-daemon/resume
            - ./transmission/torrents:/var/lib/transmission-daemon/.config/transmission-daemon/torrents
```

**Comment by demianrey** [comment]
> It might be the `nfs-transmission-downloads` volume that is hanging it up. The docker-compose.yml file is configured to mount a remote nfs volume to store Transmission downloads.
> 
> Can you please comment out the entire `volumes:` section in the top of your `docker-compose.yml` and also comment out the `- nfs-transmission-downloads:` line in `volumes:` section in the bottom of your `docker-compose.yml`?
> 
> ```yaml
> version: '3'
> 
> # volumes:
> #     nfs-transmission-downloads:
> #         driver: local
> #         driver_opts:
> #             type: nfs
> #             o: addr=192.168.168.40,rw
> #             device: ":/volume1/Transmission/downloads"
> 
> services:
>     purevpn:
>         build: ./build
>         image: jtmotox/purevpn-proxy:latest
>         container_name: purevpn-proxy
>         env_file: my.env
>         hostname: purevpn-proxy
>         privileged: true
>         restart: "no"
>         ports:
>             - "1080:1080" # socks5 proxy
>             - "9091:9091" # transmission
>         volumes:
>             - /etc/localtime:/etc/localtime:ro
>             - ./build/scripts:/scripts
>             # - nfs-transmission-downloads:/var/lib/transmission-daemon/downloads
>             - ./transmission/resume:/var/lib/transmission-daemon/.config/transmission-daemon/resume
>             - ./transmission/torrents:/var/lib/transmission-daemon/.config/transmission-daemon/torrents
> ```
**now it finished the installation, but it shows another error**

![image](https://user-images.githubusercontent.com/48655207/150471893-69650a52-a6ee-4b95-8ba7-6238bb616d38.png)

![image](https://user-images.githubusercontent.com/48655207/150472275-04689ecc-342a-461c-b963-7c39870b067b.png)

**Comment by JtMotoX** [comment]
When I use the `MX` Geo then I also get the pure021 error.  Can you please try another Geo like `DE` and let me know if that works?  If you ever have issues connecting to PureVPN, trying another Geo is always the 1st troubleshooting step.

**Comment by demianrey** [comment]
> When I use the `MX` Geo then I also get the pure021 error. Can you please try another Geo like `DE` and let me know if that works? If you ever have issues connecting to PureVPN, trying another Geo is always the 1st troubleshooting step.

With DE it works correctly, I put MX because I see that it supports Mexico, I don't understand why it doesn't connect, anyway... could you please tell me what I have to modify so that the proxy is only local to the server
